service: csv-processing-service

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  timeout: 60
  memorySize: 512
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - arn:aws:s3:::your-source-bucket/*
        - arn:aws:s3:::your-error-bucket/*
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: !Ref SNSTopic

functions:
  processCsv:
    handler: handler.lambda_handler
    events:
      - s3:
          bucket: your-source-bucket
          event: s3:ObjectCreated:*
      - http:
          path: process
          method: post
          cors: true

  notifySuccess:
    handler: handler.notify_success
    events:
      - sns:
          topicName: CsvProcessingSuccess

  notifyFailure:
    handler: handler.notify_failure
    events:
      - sns:
          topicName: CsvProcessingFailure

stepFunctions:
  stateMachines:
    CsvProcessingWorkflow:
      definition:
        Comment: "CSV Processing Step Function"
        StartAt: ProcessCsv
        States:
          ProcessCsv:
            Type: Task
            Resource: !GetAtt ProcessCsvLambdaFunction.Arn
            Next: ValidateResults
          ValidateResults:
            Type: Choice
            Choices:
              - Variable: "$.success"
                BooleanEquals: true
                Next: NotifySuccess
              - Variable: "$.success"
                BooleanEquals: false
                Next: NotifyFailure
          NotifySuccess:
            Type: Task
            Resource: !GetAtt NotifySuccessLambdaFunction.Arn
            End: true
          NotifyFailure:
            Type: Task
            Resource: !GetAtt NotifyFailureLambdaFunction.Arn
            End: true

resources:
  Resources:
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: CsvProcessingSuccess
    SNSTopicFailure:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: CsvProcessingFailure